language: c
dist: bionic
os: linux

addons:
  apt:
    update: true
    packages:
      - autoconf
      - autoconf-archive
      - automake
      - build-essential
      - cmake
      - gfortran
      - libhdf5-openmpi-dev
      - libopenmpi-dev
      - libtool-bin
      - m4
      - openmpi-bin

before_install:
  # The default environment variable $CC is known to interfere with
  # MPI projects.
  - test -n $CC && unset CC
  - (cd $HOME/spack; git describe) || git clone https://github.com/spack/spack $HOME/spack
  # Create packages.yaml to prevent building dependencies that time out
  - |
    test -f $HOME/spack/etc/spack/packages.yaml || cat > $HOME/spack/etc/spack/packages.yaml << '  EOF'
    packages:
      all:
        target: [x86_64]
        providers:
            mpi: [openmpi]
      autoconf:
        buildable: False
        externals:
        - spec: "autoconf@2.69"
          prefix: /usr
      automake:
        buildable: False
        externals:
        - spec: "automake@1.15.1"
          prefix: /usr
      cmake:
        buildable: False
        externals:
        - spec: "cmake@3.12.4"
          prefix: /usr/local/cmake-3.12.4
      libtool:
        buildable: False
        externals:
        - spec: "libtool@2.4.6"
          prefix: /usr
      m4:
        buildable: False
        externals:
        - spec: "m4@1.4.18"
          prefix: /usr
      openmpi:
        buildable: False
        externals:
        - spec: "openmpi@2.1.1"
          prefix: /usr
    EOF

install:
  - . $HOME/spack/share/spack/setup-env.sh
  - spack install gotcha@1.0.3 && spack load gotcha@1.0.3
  - spack install margo^mercury@1.0.1+bmi~ofi~boostsys && spack load argobots && spack load mercury && spack load margo
  - spack install spath && spack load spath
  # prepare build environment
  - eval $(./scripts/git_log_test_env.sh)
  - export TEST_CHECKPATCH_SKIP_FILES

cache:
  directories:
    - $HOME/spack

# Don't update the cache just because the spack lock file changed
before_cache:
  - rm -f $HOME/spack/opt/spack/.spack-db/prefix_lock

script:
  # Force git to update the shallow clone and include tags so git-describe works
  - git fetch --unshallow --tags
  - export DISTCHECK_CONFIGURE_FLAGS="--enable-fortran"
  - ./autogen.sh
  - ./configure $DISTCHECK_CONFIGURE_FLAGS || cat config.log
  - make distcheck V=1
  - ./scripts/checkpatch.sh || test "$TEST_CHECKPATCH_ALLOW_FAILURE" = yes

after_failure:
  - find . -type f -name "test-suite.log" -execdir cat {} \;
